apiVersion: v1 
kind: ReplicationController
metadata:
  name: nginx-rc

spec:
  replicas: 3
  selector:
    app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      initContainers:
        - name: init1
          image: busybox
          command: ["echo","Kubernetes Is fun~~!!"]
         
      containers:
      - name: nginx 
        image: nginx 
        ports:
        - containerPort: 80

